# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='diponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name_plural': 'e-mails',
                'verbose_name': 'e-mail',
                'ordering': ('-criado_em',),
            },
        ),
    ]
