# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 17:25
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='texto_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=stdimage.models.StdImageField(default='img/no-img.jpg', help_text='Tamanho da imagem: 1600x1038 pixeis.', max_length=200, upload_to='uploads/banners/', verbose_name='imagem'),
        ),
    ]
